brichki/ads/urls.py
from django.urls import path, include

from . import views


app_name = 'ads'


urlpatterns = [
    path('', views.FilterView.as_view(), name='filter'),
    path('ad/<slug:pk>', views.AdView.as_view(), name='ad'),

    path('api/ad_list/', views.AdListAPIView.as_view()),
    path('api/ad_create/', views.AdCreateAPIView.as_view()),
    path('api/ad_rud/<slug:pk>/', 
        views.AdRetrieveUpdateDestroyAPIView.as_view()),
]

brichki/brichki/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

import ads.urls
import users.urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(ads.urls)),
    path('users/', include(users.urls)),

    path('api/drf_auth/', include('rest_framework.urls', 
        namespace='rest_framework')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

brichki/users/urls.py
from django.urls import path, include
from rest_framework import routers

from . import views


app_name = 'users'


router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)

urlpatterns = [
    path('reg/', views.CreateUserView.as_view(), name='reg'),
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('logout/', views.LogoutUserView.as_view(), name='logout'),
    path('account/', views.UserView.as_view(), name='account'),
    path('create_ad/', views.CreateAdView.as_view(), name='create_ad'),
    path('update_ad/<slug:pk>', views.UpdateAdView.as_view(), 
        name='update_ad'),
    path('delete_ad/<slug:pk>', views.DeleteAdView.as_view(), 
        name='delete_ad'),
    path('api/', include(router.urls)),
]

brichki/users/models.py
from django.db import models


# Create your models here.

brichki/users/forms.py
from django import forms
from django.forms import ModelForm 
from ads.models import Ad


class AdCreateForm(ModelForm):
	class Meta:
		model = Ad
		fields = (
			'brand', 'model', 'generation', 'body', 'engine_type', 
			'boost_type', 'drive', 'broken', 'comment', 
			'engine_capacity', 'mileage', 'price')

class AdUpdateForm(ModelForm):
	class Meta:
		model = Ad
		fields = (
			'brand', 'model', 'generation', 'body', 'engine_type', 
			'boost_type', 'drive', 'broken', 'comment', 
			'engine_capacity', 'mileage', 'price')

brichki/users/views.py
from django.views.generic import (
    CreateView, UpdateView, TemplateView, DeleteView,
    )
from django.contrib.auth.views import LogoutView, LoginView 

from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse

from django.core.exceptions import PermissionDenied

from django.contrib.auth.models import User
from rest_framework import viewsets

from .serializers import UserSerializer

from . import forms
from ads.models import Ad


class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer


class CreateUserView(CreateView):
    template_name = 'users/reg.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('users:account')

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('users:account')
        return super().get(request, *args, **kwargs)


class LoginUserView(LoginView):
    template_name = 'users/login.html'
    authentication_form = AuthenticationForm
    next_page = 'users:account'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('users:account')
        return self.render_to_response(self.get_context_data())


class LogoutUserView(LogoutView):
    next_page = 'users:login'


@method_decorator(login_required(), name='dispatch')
class UserView(TemplateView):
    template_name = 'users/account.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['own_ads'] = Ad.objects.filter(
        author=self.request.user.id
            ).select_related(
            'brand', 'model', 'generation', 'body', 'engine_type', 
            'boost_type', 'drive', 'broken',
            )
        return context


@method_decorator(login_required(), name='dispatch')
class CreateAdView(CreateView):
    template_name = 'users/create_ad.html'
    form_class = forms.AdCreateForm
    success_url = reverse_lazy('users:account')

    def form_valid(self, form, *args, **kwargs):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return super(CreateAdView, self).form_valid(form)


@method_decorator(login_required(), name='dispatch')
class UpdateAdView(UpdateView):
    model = Ad
    template_name = 'users/update_ad.html'
    form_class = forms.AdUpdateForm
    success_url = reverse_lazy('users:account')

    def get_object(self, queryset=None):
        obj = super(UpdateAdView, self).get_object()
        
        if not obj.author == self.request.user:
            raise PermissionDenied
        return obj    

    def get(self, request, *args, **kwargs):
        try:
            self.object = self.get_object()
        except PermissionDenied:
            return redirect('users:account')
        
        return super().get(request, *args, **kwargs)


@method_decorator(login_required(), name='dispatch')
class DeleteAdView(DeleteView):
    model = Ad
    template_name = 'users/delete_ad.html'  
    success_url = reverse_lazy('users:account')
    
    def get_object(self, queryset=None):
        obj = super(DeleteAdView, self).get_object()

        if not obj.author == self.request.user:
            raise PermissionDenied
        return obj

    def get(self, request, *args, **kwargs):
        try:
            self.object = self.get_object()
        except PermissionDenied:
            return redirect('users:account')
        
        return super().get(request, *args, **kwargs)

brichki/users/templates/users/account.html
{% extends 'brichki/base.html' %}


{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static 'users/css/users.css' %}" />

<div class="box">
	<form method="post" class="box">
		{% csrf_token %}
		<p>Имя: {{ user.username }}</p>
		<p>Дата регистрации: {{ user.date_joined }}</p>
		<button formmethod="post" formaction="{% url 'users:logout' %}" formnovalidate class="user-button">
			Выйти</button><br>
	</form>
	<a href="{% url 'users:create_ad' %}">
		<div class="box create-ad-link">
			<span>Создать объявление</span>
		</div>
	</a>

	{% for ad in own_ads %}
	<a class="own-ad-link" href="{% url 'ads:ad' pk=ad.pk %}">
		<div class="box">
			<div class="own-ad">
		        <div class="container">
		            <div class="own-ad-photo box">photo</div>
		            <div class="own-ad-container">
		                <div class="own-ad-row">
		                    <span class="own-ad-item">{{ ad.brand }}</span>
		                    <span class="own-ad-item">{{ ad.model }}</span>
		                    <span class="own-ad-item">{{ ad.generation }}</span>
		                </div>
		                <div class="own-ad-row">
		                    <span class="own-ad-item">{{ ad.body }}</span>
		                    <span class="own-ad-item">{{ ad.engine_type }}</span>
		                    <span class="own-ad-item">{{ ad.boost_type }}</span>
		                </div>
		                <div class="own-ad-row">
		                    <span class="own-ad-item">{{ ad.drive }}</span>
		                    <span class="own-ad-item">{{ ad.broken }}</span>
		                    <span class="own-ad-item">{{ ad.price }}</span>
		                </div>
		            </div>
		        </div>
		        <div class="own-box-links">
                    <a class="own-link" href="{% url 'users:update_ad' pk=ad.pk %}">Изменить</a>
                    <a class="own-link" href="{% url 'users:delete_ad' pk=ad.pk %}">Удалить</a>
		        </div>
		    </div>
		</div>
	</a>
	{% endfor %}

</div>

{% endblock %}

brichki/users/templates/users/create_ad.html
{% extends 'brichki/base.html' %}


{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static 'users/css/users.css' %}" />

<div class="box">
	<form method="post" class="box">
		{% csrf_token %}
		<p>user: <b><u>{{ user }}</u></b></p>
		{{ form.as_p }}
		<button type="submit" class="user-button">Создать объявление</button>
	</form>
</div>

{% endblock %}

brichki/users/templates/users/delete_ad.html
{% extends 'brichki/base.html' %}


{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static 'users/css/users.css' %}" />

<div class="box">
	<form method="post" class="box">
		{% csrf_token %}
		<p>{{ ad }}</p>
		<button type="submit" class="user-button">Удалить объявление</button>
	</form>
</div>

{% endblock %}

brichki/users/templates/users/login.html
{% extends 'brichki/base.html' %}


{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static 'users/css/users.css' %}" />

<div class="box">
	<form method="post" class="box">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" class="user-button">Войти</button>
	</form>
</div>

{% endblock %}

brichki/users/templates/users/reg.html
{% extends 'brichki/base.html' %}


{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static 'users/css/users.css' %}" />

<div class="box">
	<form method="post" class="box">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" class="user-button">Зарегистрироваться</button>
	</form>
</div>

{% endblock %}

brichki/users/templates/users/update_ad.html
{% extends 'brichki/base.html' %}


{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static 'users/css/users.css' %}" />

<div class="box">
	<form method="post" class="box">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" class="user-button">Изменить объявление</button>
	</form>
</div>

{% endblock %}