brichki/ads/urls.py
from django.urls import path, include

from . import views


app_name = 'ads'


urlpatterns = [
    path('', views.FilterView.as_view(), name='filter'),
    path('ad/<slug:pk>', views.AdView.as_view(), name='ad'),

    path('api/ad_list/', views.AdListAPIView.as_view()),
    path('api/ad_create/', views.AdCreateAPIView.as_view()),
    path('api/ad_rud/<slug:pk>/', 
        views.AdRetrieveUpdateDestroyAPIView.as_view()),
]

brichki/brichki/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

import ads.urls
import users.urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(ads.urls)),
    path('users/', include(users.urls)),

    path('api/drf_auth/', include('rest_framework.urls', 
        namespace='rest_framework')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

brichki/users/urls.py
from django.urls import path, include
from rest_framework import routers

from . import views


app_name = 'users'


router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)

urlpatterns = [
    path('reg/', views.CreateUserView.as_view(), name='reg'),
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('logout/', views.LogoutUserView.as_view(), name='logout'),
    path('account/', views.UserView.as_view(), name='account'),
    path('create_ad/', views.CreateAdView.as_view(), name='create_ad'),
    path('update_ad/<slug:pk>', views.UpdateAdView.as_view(), 
        name='update_ad'),
    path('delete_ad/<slug:pk>', views.DeleteAdView.as_view(), 
        name='delete_ad'),
    path('api/', include(router.urls)),
]

brichki/templates/brichki/base.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <title>Brichki.ru</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'brichki/css/base.css' %}" />
    </head>
    <body>
        <div class="header">
            <div class="container">
                <a class="item header-link" href="{% url 'ads:filter' %}">Brichki.ru</a>
                <a class="item header-link" href="{% url 'users:account' %}">
                    {% if user.is_authenticated %}
                        {{ user.username }}
                    {% else %}
                        Войти
                    {% endif %}
                </a>
            </div>
        </div>

        {% block content %}
        {% endblock %}

        <div class="footer">
            <span class="item">vladwgm@gmail.com</span>
        </div>
    </body>
</html>